#!/bin/bash

xdotool search --onlyvisible --classname URxvtFuzzy windowunmap \
  || xdotool search --classname URxvtFuzzy windowmap \
  || urxvtc -name URxvtFuzzy -geometry 40x8+297+1 -e sh -c 'compgen -c | sort -u | fzf | sh'